---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helloworld-pv
  namespace: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:          # Using hostPath for local storage, you can change it to a cloud provider-specific one if needed.
    path: "/mnt/data/pvc/helloworld"  # Specify the path on the host node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
